language = "programming fundamentals"
print (len(language))
print (language[0])
print (language[2])
print (language[3])
print (language[4])
print (language[9])
print (language[13])
print (language[0:])
print (language[:24])